USE [master]
GO
/****** Object:  Database [[STUDENTSMANAGEMENT]]    Script Date: 3/6/2025 21:21 ******/
CREATE DATABASE [STUDENTSMANAGEMENT]
CONTAINMENT = NONE
ON PRIMARY 
(
  NAME = N'STUDENTS_MDF',
  FILENAME = N'D:\SDC_course\GUI_database_practise\poo21\STUDENTS.mdf',
  SIZE = 8192KB,
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 65536KB
)
LOG ON 
(
  NAME = N'STUDENTS_LOG',
  FILENAME = N'D:\SDC_course\GUI_database_practise\poo21\STUDENTS.ldf',
  SIZE = 8192KB,
  MAXSIZE = 2048GB,
  FILEGROWTH = 65536KB
)
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STUDENTSMANAGEMENT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ARITHABORT OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET  MULTI_USER 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET QUERY_STORE = ON
GO
ALTER DATABASE [STUDENTSMANAGEMENT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [STUDENTSMANAGEMENT]
GO
/****** Object:  Table [dbo].[account]    Script Date: 3/6/2025 21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[students](
	[id] [nvarchar](50) NOT NULL,
	[studentname] [nvarchar](50) NOT NULL,
	[semester] [nvarchar](255) NOT NULL,
	[coursename] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO