# -*- coding: utf-8 -*-
from tkinter.messagebox import YESNO

# Form implementation generated from reading ui file 'create_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pyodbc

from PyQt5 import QtCore, QtGui, QtWidgets
from home import Home

class CreateStudent(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(37)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 2, 3)
        self.backbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.backbtn.setFont(font)
        self.backbtn.setObjectName("backbtn")
        self.gridLayout.addWidget(self.backbtn, 8, 1, 1, 1)
        self.createstudentbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.createstudentbtn.setFont(font)
        self.createstudentbtn.setObjectName("createstudentbtn")
        self.gridLayout.addWidget(self.createstudentbtn, 6, 1, 1, 1)
        self.exitbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitbtn.setFont(font)
        self.exitbtn.setObjectName("exitbtn")
        self.gridLayout.addWidget(self.exitbtn, 10, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(36)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.idlineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.idlineedit.setObjectName("idlineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idlineedit)
        self.studentname_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.studentname_lineedit.setObjectName("studentname_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.studentname_lineedit)
        self.coursename_ledit = QtWidgets.QLineEdit(self.centralwidget)
        self.coursename_ledit.setObjectName("coursename_ledit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.coursename_ledit)
        self.semester_ledit = QtWidgets.QLineEdit(self.centralwidget)
        self.semester_ledit.setObjectName("semester_ledit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.semester_ledit)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 3, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.createstudentbtn.clicked.connect(self.addStudent)
        self.backbtn.clicked.connect(self.back_response)
        self.exitbtn.clicked.connect(self.exit_response)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def addStudent(self):
        list_coursename=['java','python','.net','.Net']
        student_id = self.idlineedit.text()
        student_name = self.studentname_lineedit.text()
        course_name = self.coursename_ledit.text()
        semester = self.semester_ledit.text()

        student_id=student_id.isnumeric()
        student_name=student_name.isalnum()
        course_name=course_name.isalnum()
        semester=semester.isnumeric()
        conn_result=False

        if student_id==True and student_name==False and course_name==False and semester==True:
            if course_name.lower() in list_coursename:
                server = 'DESKTOP-PICVBQP\SQLEXPRESS'
                database = 'STUDENTSMANAGEMENT'
                try:
                    conn = pyodbc.connect(f'DRIVER={{ODBC Driver 17 for SQL Server}};'
                                          f'SERVER={server};'
                                          f'DATABASE={database};'
                                          f'Trusted_Connection=yes;')
                    cursor = conn.cursor()
                    print("Connection established")
                    insert_query = "INSERT INTO dbo.students (id, studentname, semester, coursename) VALUES (?, ?, ?, ?)"
                    cursor.execute(insert_query, student_id, student_name, semester, course_name)
                    conn.commit()
                    QtWidgets.QMessageBox.information(None, "Success", "Student added successfully!")
                    print("adding successfully")
                    self.idlineedit.clear()
                    self.studentname_lineedit.clear()
                    self.coursename_ledit.clear()
                    self.semester_ledit.clear()


                except pyodbc.IntegrityError as e:
                    QtWidgets.QMessageBox.critical(None, "SQL Error", "Lỗi: ID bị trùng hoặc sai định dạng.\n" + str(e))
                except pyodbc.Error as e:
                    QtWidgets.QMessageBox.critical(None, "SQL Error", str(e))
                except Exception as e:
                    QtWidgets.QMessageBox.critical(None, "Unexpected Error", str(e))
                finally:
                    try:
                        conn.close()
                    except:
                        pass
            else:
                QtWidgets.QMessageBox.information(None, "Error", "We don't have your course name")
        elif student_id=="" or student_name=="" or course_name=="" or semester=="":
            print("Please fill in your information")
        else:
            QtWidgets.QMessageBox.information(None, "Error", "Please check your information again")

    def back_response(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Home()
        self.ui.setupUi(self.window)
        self.window.show()

    def exit_response(self):
        sys.exit(app.exec_())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "WELCOME TO STUDENT MANAGEMENT"))
        self.backbtn.setText(_translate("MainWindow", "Back"))
        self.createstudentbtn.setText(_translate("MainWindow", "Create"))
        self.exitbtn.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "ID: "))
        self.label_4.setText(_translate("MainWindow", "Student Name"))
        self.label_3.setText(_translate("MainWindow", "Semester"))
        self.label_5.setText(_translate("MainWindow", "Courrse name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = CreateStudent()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
